logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: INFO
server:
  port: 8080
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    sqlScriptEncoding: UTF-8
    url: jdbc:h2:mem:searchbooks;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    chain:
      cache: false
